In [1]:
import os
print(os.getcwd())

c:\Users\SCI\Desktop\AI-Credit-Risk-Lending-Decision-Engine\notebooks

In [2]:
df = pd.read_csv("../data/processed/credit_risk_scored.csv")
print(df.shape)

NameError: name 'pd' is not defined

In [3]:
import pandas as pd
import joblib

print("Libraries Loaded")

Libraries Loaded

In [4]:
df = pd.read_csv("../data/processed/credit_risk_scored.csv")

print(df.shape)

(44006, 33)

In [5]:
model = joblib.load(
    "../models/logistic_regression_model.pkl"
)

scaler = joblib.load(
    "../models/scaler.pkl"
)

print("Model Loaded")

Model Loaded

In [6]:
model = joblib.load(
    "../models/logistic_regression_model.pkl"
)

print(model.coef_.shape)

(1, 27)

In [7]:
feature_names = df.drop(
    [
        "default",
        "risk_score",
        "risk_category",
        "decision",
        "risk_category_v2",
        "decision_v2"
    ],
    axis=1
).columns

print(len(feature_names))
print(feature_names.tolist())

27
['loan_amnt', 'annual_inc', 'dti', 'int_rate', 'installment', 'avg_fico', 'emp_length_num', 'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT', 'purpose_credit_card', 'purpose_debt_consolidation', 'purpose_home_improvement', 'purpose_house', 'purpose_major_purchase', 'purpose_medical', 'purpose_moving', 'purpose_other', 'purpose_renewable_energy', 'purpose_small_business', 'purpose_vacation', 'grade_B', 'grade_C', 'grade_D', 'grade_E', 'grade_F', 'grade_G']

In [8]:
importance_df = pd.DataFrame(
    {
        "feature": feature_names,
        "coefficient": model.coef_[0]
    }
)

importance_df

                       feature  coefficient
0                    loan_amnt     0.780899
1                   annual_inc    -0.072591
2                          dti     0.168056
3                     int_rate     0.801343
4                  installment    -0.689747
5                     avg_fico    -0.162043
6               emp_length_num    -0.001058
7      home_ownership_MORTGAGE    -0.084230
8           home_ownership_OWN     0.021664
9          home_ownership_RENT     0.078471
10         purpose_credit_card     0.068871
11  purpose_debt_consolidation     0.083637
12    purpose_home_improvement     0.050332
13               purpose_house     0.002739
14      purpose_major_purchase     0.036041
15             purpose_medical     0.021822
16              purpose_moving     0.001478
17               purpose_other    -0.021800
18    purpose_renewable_energy    -0.012271
19      purpose_small_business     0.019087
20            purpose_vacation     0.007670
21                     grade_B     0.113508
22                     grade_C     0.094670
23                     grade_D     0.022117
24                     grade_E    -0.030985
25                     grade_F    -0.071553
26                     grade_G    -0.065111

In [9]:
importance_df = importance_df.sort_values(
    by="coefficient",
    ascending=False
)

importance_df.head(10)

                       feature  coefficient
3                     int_rate     0.801343
0                    loan_amnt     0.780899
2                          dti     0.168056
21                     grade_B     0.113508
22                     grade_C     0.094670
11  purpose_debt_consolidation     0.083637
9          home_ownership_RENT     0.078471
10         purpose_credit_card     0.068871
12    purpose_home_improvement     0.050332
14      purpose_major_purchase     0.036041

In [10]:
importance_df.tail(10)

                     feature  coefficient
6             emp_length_num    -0.001058
18  purpose_renewable_energy    -0.012271
17             purpose_other    -0.021800
24                   grade_E    -0.030985
26                   grade_G    -0.065111
25                   grade_F    -0.071553
1                 annual_inc    -0.072591
7    home_ownership_MORTGAGE    -0.084230
5                   avg_fico    -0.162043
4                installment    -0.689747

In [11]:
def explain_applicant(row):

    reasons = []

    if row["int_rate"] > 15:
        reasons.append("High Interest Rate")

    if row["dti"] > 20:
        reasons.append("High Debt-to-Income Ratio")

    if row["avg_fico"] < 680:
        reasons.append("Low FICO Score")

    if row["annual_inc"] < 50000:
        reasons.append("Lower Annual Income")

    if row["loan_amnt"] > 15000:
        reasons.append("Large Loan Amount")

    return reasons

In [12]:
sample = df.iloc[0]

print(explain_applicant(sample))

['Low FICO Score']

In [13]:
sample = df.iloc[10]

print(explain_applicant(sample))

['High Interest Rate', 'Low FICO Score', 'Large Loan Amount']

In [14]:
df["risk_reasons"] = df.apply(
    explain_applicant,
    axis=1
)

df[
    [
        "risk_score",
        "decision_v2",
        "risk_reasons"
    ]
].head(10)

   risk_score decision_v2                                      risk_reasons
0        18.0     Approve                                  [Low FICO Score]
1        13.0     Approve                               [Large Loan Amount]
2        19.0     Approve                               [Large Loan Amount]
3        45.0      Reject   [High Interest Rate, High Debt-to-Income Ratio]
4        22.0      Review                             [Lower Annual Income]
5         9.0     Approve                               [Large Loan Amount]
6         9.0     Approve                               [Large Loan Amount]
7         6.0     Approve                                                []
8        17.0     Approve  [High Debt-to-Income Ratio, Lower Annual Income]
9        16.0     Approve                       [High Debt-to-Income Ratio]

In [15]:
df[
    [
        "risk_score",
        "decision_v2",
        "risk_reasons"
    ]
].head(10)

   risk_score decision_v2                                      risk_reasons
0        18.0     Approve                                  [Low FICO Score]
1        13.0     Approve                               [Large Loan Amount]
2        19.0     Approve                               [Large Loan Amount]
3        45.0      Reject   [High Interest Rate, High Debt-to-Income Ratio]
4        22.0      Review                             [Lower Annual Income]
5         9.0     Approve                               [Large Loan Amount]
6         9.0     Approve                               [Large Loan Amount]
7         6.0     Approve                                                []
8        17.0     Approve  [High Debt-to-Income Ratio, Lower Annual Income]
9        16.0     Approve                       [High Debt-to-Income Ratio]

In [16]:
def explain_applicant(row):

    reasons = []

    if row["int_rate"] > 15:
        reasons.append("High Interest Rate")

    if row["dti"] > 20:
        reasons.append("High Debt-to-Income Ratio")

    if row["avg_fico"] < 680:
        reasons.append("Low FICO Score")

    if row["annual_inc"] < 50000:
        reasons.append("Lower Annual Income")

    if row["loan_amnt"] > 15000:
        reasons.append("Large Loan Amount")

    if len(reasons) == 0:
        reasons.append("Strong Overall Credit Profile")

    return reasons

In [17]:
df["risk_reasons"] = df.apply(
    explain_applicant,
    axis=1
)

In [18]:
df.to_csv(
    "../data/processed/credit_risk_explainable.csv",
    index=False
)

print("Explainable dataset saved")

Explainable dataset saved